### ISSUE TITLE
CSS Ideas

### ISSUE THREAD

**Issue by eignnx** [LeviBuckwalter/Rule34-Advanced-Search#2]
```css
/* Inline #1 | https://levibuckwalter.github.io/Rule34-Advanced-Search/html_and_css/tagComparison.html */

button {
  color: ;
  background: transparent;
  padding: 0.5rem;
}

html {
  background: darkolivegreen;
}

button {
  color: white;
  border: 3px solid white;
  border-radius: 6px;
}

button:hover {
  color: black;
  background: white;
}

button {
  transition: all ease-in-out 100ms;
}

a {
  font-family: monospace;
  font-weight: bolder;
}

a:visited {
  color: darkgrey;
}

a:hover {
  color: pink;
}

a {
  color: greenyellow;
}

html {
  font-family: sans-serif;
  font-weight: 600;
}

#results {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 1rem;
}

html {
  color: #f6facf;
}

body {
  margin-inline: 1rem;
}

/* Element | https://levibuckwalter.github.io/Rule34-Advanced-Search/html_and_css/tagComparison.html */

#results > div:nth-child(2) {
  /* padding-top: -1px; */
  /* padding-top: 10rem; */
  /* padding-left: rem; */
}
```
